unity_topic: '/uav1/unity_sensors/camera'
sphinx_topic: '/uav1/sphinx_sensors/camera'
real_topic: '/uav1/physical_sensors/camera'

camera_overlay_source: '/uav1/unity_sensors/camera'

camera_base: "/uav1/physical_sensors/camera"
camera_overlay: False