sphinx_topic: '/uav1/sphinx_sensors/camera'
unity_topic: '/uav1/unity_sensors/camera'
real_topic: '/uav1/physical_sensors/camera'

attitude_source_use_tlm: ""
attitude_source_use_sphinx_firmware: "/uav1/sphinx_sensors/attitude"
attitude_source_use_physical_firmware: "/uav1/physical_sensors/attitude"
attitude_source_use_vicon: "vicon"

position_source_use_tlm: ""
position_source_use_sphinx_firmware: "/uav1/sphinx_sensors/position"
position_source_use_physical_firmware: "/uav1/physical_sensors/position"
position_source_use_vicon: "vicon"




camera_overlay: True
camera_base: "/uav1/sphinx_sensors/camera"
camera_overlay_source: '/uav1/unity_sensors/camera'

attitude_source: ""
position_source: ""